### ISSUE TITLE
O que seria isso?

### ISSUE THREAD

**Issue by De4dm4sterBR** [nageseio/RBot#1]
Consegue explicar por que teu bot meche com isso?

C:\Documents and Settings\Administrator\Local Settings\Temp\EB93A6\996E.exe

**Comment by nageseio** [comment]
Uma ponte de conexão com a internet, pra baixar atualizaçoes. Toda vez que o bot é executado verifica se existe atualização.

**Comment by De4dm4sterBR** [comment]
Não consigo usar. Eu abro ele, ele baixa o update e fica num loop infinito de download do update.

**Comment by nageseio** [comment]
Essa versão, por enquanto, esta desativada.
A versão atual e funcional é esta --> https://github.com/nageseio/RBot-Beta.
